import { Component, inject, OnInit } from '@angular/core';
import { IDownloadFilePayload, IOpenURLPayload, IReadDataPayload, IResponseMessage, IShowNotificationPayload, IStoreDataPayload, IVerifyBiometricSignaturePayload, IWriteToConsolePayload, MESSAGE_ACTIONS } from '../../../models/webview-bridge.models';
import { WebviewBridgeService } from '../../../services/webview-bridge.service';

@Component({
  selector: 'app-react-native-message-test',
  standalone: false,
  templateUrl: './react-native-message-test.component.html',
  styleUrl: './react-native-message-test.component.scss'
})
export class ReactNativeMessageTestComponent implements OnInit {
  private readonly _webviewBridgeService = inject(WebviewBridgeService);
  nativeAppIsAvailable = false;
  isLoading = false;
  result: any = null;
  resultSource: string = '';
  public readonly reactNativeActions = [
    MESSAGE_ACTIONS.WRITE_TO_CONSOLE,
    MESSAGE_ACTIONS.STORE_DATA,
    MESSAGE_ACTIONS.READ_DATA,
    MESSAGE_ACTIONS.GET_BIOMETRIC_AVAILABILITY,
    MESSAGE_ACTIONS.VERIFY_BIOMETRIC_SIGNATURE,
    MESSAGE_ACTIONS.GET_NOTIFICATION_TOKEN,
    MESSAGE_ACTIONS.GET_MOBILE_SERIAL_NUMBER,
    MESSAGE_ACTIONS.GET_PLATFORM_INFO,
    MESSAGE_ACTIONS.SHOW_NOTIFICATION,
    MESSAGE_ACTIONS.DOWNLOAD_FILE,
    MESSAGE_ACTIONS.OPEN_URL,
  ];

  ngOnInit(): void {
    this.nativeAppIsAvailable = this._webviewBridgeService.nativeAppIsAvailable();
  }

  onReactNativeMessage(action: MESSAGE_ACTIONS) {
    this.result = null;
    this.resultSource = '';
    let requestPayload = null;

    switch (action) {
      case MESSAGE_ACTIONS.WRITE_TO_CONSOLE:
        {
          const payload: IWriteToConsolePayload = {
            level: 'warn',
            message: 'test warning message from website'
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.STORE_DATA:
        {
          const payload: IStoreDataPayload = {
            key: 'website-data-key',
            value: {
              a: 10,
              b: '15'
            }
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.READ_DATA:
        {
          const payload: IReadDataPayload = {
            key: 'website-data-key',
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.VERIFY_BIOMETRIC_SIGNATURE:
        {
          const payload: IVerifyBiometricSignaturePayload = {
            promptMessage: 'בדיקה'
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.SHOW_NOTIFICATION:
        {
          const payload: IShowNotificationPayload = {
            title: 'בדיקה',
            body: 'הודעת בדיקה',
            data: {
              isTest: "true",
              source: "developer.react-native-message-test"
            },
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.DOWNLOAD_FILE:
        {
          const payload: IDownloadFilePayload = {
            fileName: 'Book1.xlsx',
            mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            base64: 'UEsDBBQABgAIAAAAIQBBN4LPbgEAAAQFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsVMluwjAQvVfqP0S+Vomhh6qqCBy6HFsk6AeYeJJYJLblGSj8fSdmUVWxCMElUWzPWybzPBit2iZZQkDjbC76WU8kYAunja1y8T39SJ9FgqSsVo2zkIs1oBgN7+8G07UHTLjaYi5qIv8iJRY1tAoz58HyTulCq4g/QyW9KuaqAvnY6z3JwlkCSyl1GGI4eINSLRpK3le8vFEyM1Ykr5tzHVUulPeNKRSxULm0+h9J6srSFKBdsWgZOkMfQGmsAahtMh8MM4YJELExFPIgZ4AGLyPdusq4MgrD2nh8YOtHGLqd4662dV/8O4LRkIxVoE/Vsne5auSPC/OZc/PsNMilrYktylpl7E73Cf54GGV89W8spPMXgc/oIJ4xkPF5vYQIc4YQad0A3rrtEfQcc60C6Anx9FY3F/AX+5QOjtQ4OI+c2gCXd2EXka469QwEgQzsQ3Jo2PaMHPmr2w7dnaJBH+CW8Q4b/gIAAP//AwBQSwMEFAAGAAgAAAAhALVVMCP0AAAATAIAAAsACAJfcmVscy8ucmVscyCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACskk1PwzAMhu9I/IfI99XdkBBCS3dBSLshVH6ASdwPtY2jJBvdvyccEFQagwNHf71+/Mrb3TyN6sgh9uI0rIsSFDsjtnethpf6cXUHKiZylkZxrOHEEXbV9dX2mUdKeSh2vY8qq7iooUvJ3yNG0/FEsRDPLlcaCROlHIYWPZmBWsZNWd5i+K4B1UJT7a2GsLc3oOqTz5t/15am6Q0/iDlM7NKZFchzYmfZrnzIbCH1+RpVU2g5abBinnI6InlfZGzA80SbvxP9fC1OnMhSIjQS+DLPR8cloPV/WrQ08cudecQ3CcOryPDJgosfqN4BAAD//wMAUEsDBBQABgAIAAAAIQAgRXe+ZAMAAKkIAAAPAAAAeGwvd29ya2Jvb2sueG1srFVtb5s6GP1+pfsfEN8pNi8JoNIpvOlWaqcqzdpNmjS5YIpVwFxjmlTV/vsek5C2yzTldjdKbGw/HJ/zPMfO6YdNU2uPVPSMt6GOT5Cu0TbnBWvvQ/3TKjM8XeslaQtS85aG+hPt9Q9nf/91uubi4Y7zBw0A2j7UKym7wDT7vKIN6U94R1tYKbloiIShuDf7TlBS9BWlsqlNC6GZ2RDW6luEQByDwcuS5TTh+dDQVm5BBK2JBPp9xbp+QmvyY+AaIh6Gzsh50wHEHauZfBpBda3Jg/P7lgtyV4PsDXa1jYDvDH4YQWNNO8HSwVYNywXveSlPANrckj7Qj5GJ8ZsUbA5zcBySYwr6yFQN96zE7J2sZnus2QsYRn+MhsFao1cCSN470dw9N0s/Oy1ZTW+21tVI130kjapUrWs16WVaMEmLUJ/DkK/pmwkxdNHAali1fMvGunm2t/OV0ApakqGWKzDyBA+ByLIRUpFgjEUtqWiJpDFvJfhwp+tPPTdixxUHh2tL+u/ABIWDBf4CrdCSPCB3/RWRlTaIOtTj4KukTff1lRHJoev/gxVJrvSZIHBLYvv8s1jgIoLJbldSaPB8nlxAyq/JIxQAylzszuc5ZNj79rxw574X25FhOygxHGxbRuTbseE5OE5sy5r5mf8dVIhZkHMyyGpXVIUZ6g5U8GDpkmymFYyCgRUv+z+j3cdQ/U/NtPZdKVXX1w2j6/6l/GqobW5ZW/B1qNug5Wk/8GG0HlduWSEr8IQ3n+/n/qHsvgK62EUqEDyuaIX6s5dEOE6t1PAW0RzUY8/w3AgZkZVEvpW4tp3ORzrmKz7jLQm8xl5rR2dfq5sTw3WsepVaeBaB2kOcF6OJzem1nNQ5OFl1Y6CPkeUryXQjL3o59mAiBvSwgxZz5DsGSm3XcDzfgrpAhWInsVJ3niZp5KriqFs++D/uutHLwfT3oVhWRMiVIPkD/OksaRmRHmy0FQR8X5ONXC9CNlB0MpxBLn1IYzRzDDfJbHeOkzh1sxeySn75zpvGM8e3KZEDnEJ1AMdxoNpsN7ufLLcTuzq9OXHBMlF53739u8BrUF/TI4OzmyMD44+Xq8sjYy/S1bfb7NjgxWWULI6PXyyXiy+r9PO0hfnLhJpjwVU72tScbHL2AwAA//8DAFBLAwQUAAYACAAAACEAgT6Ul/MAAAC6AgAAGgAIAXhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArFJNS8QwEL0L/ocwd5t2FRHZdC8i7FXrDwjJtCnbJiEzfvTfGyq6XVjWSy8Db4Z5783Hdvc1DuIDE/XBK6iKEgR6E2zvOwVvzfPNAwhi7a0egkcFExLs6uur7QsOmnMTuT6SyCyeFDjm+CglGYejpiJE9LnShjRqzjB1Mmpz0B3KTVney7TkgPqEU+ytgrS3tyCaKWbl/7lD2/YGn4J5H9HzGQlJPA15ANHo1CEr+MFF9gjyvPxmTXnOa8Gj+gzlHKtLHqo1PXyGdCCHyEcffymSc+WimbtV7+F0QvvKKb/b8izL9O9m5MnH1d8AAAD//wMAUEsDBBQABgAIAAAAIQBjSP14SwMAAHUJAAAYAAAAeGwvd29ya3NoZWV0cy9zaGVldDEueG1snJJLi9swFIX3hf4Hob2j2GM5iYkzlPEMnV3pa6/I17GIHq6kvCj97712SGYgmzAggZ7fuUc6y8ej0WQPPihnK5pOppSAla5RdlPRXz9fkjklIQrbCO0sVPQEgT6uPn9aHpzfhg4gEiTYUNEuxr5kLMgOjAgT14PFndZ5IyJO/YaF3oNoxktGs2w6LZgRytIzofT3MFzbKgm1kzsDNp4hHrSIWH/oVB8uNCPvwRnht7s+kc70iFgrreJphFJiZPm6sc6LtUbfxzQXkhw9tgz7w0VmXL9RMkp6F1wbJ0hm55pv7S/Yggl5Jd36vwuT5szDXg0f+IbKPlZSyq+s7A328EFYcYUNz+XLnWoq+jeb57zgi+ckK4pZks/yPFmkvEjqOuPPszl/mvH0H10tG4U/PLgiHtqKfknLek7Zajnm57eCQ3g3JlGsf4AGGQE1UkqGeK6d2w4HX3FpisQwHhiIQka1hyfQGsHoNPw5a2SDALsqvB9f1F7GQH/zpIFW7HT87g5fQW26iLIcbQ45KZtTDUFiQFF4knGk/gcAAP//AAAA//+UlEtqw0AQRK8i5gCRRx/bMWNB5LmIUARZOcEj7OT26XyY7ipiyOwkvVo8uroV0suyrHFapyFcXm/V5ei8q9LbdE7ydOhc9e67aT48f8Qlzct5PbrNQ9O7Icxf2ScJy6ck79dhE+rrEOr5l42WeWQny7bIomW7zGrRy45NiaOEs2NDjpa15GhZR46W9X87tiWOEs6Oe3K07JEcLfNUQASoDcAkpeH/ty3hbOl5lAB5lgB5mADvTLMv8ZSwetJ6jQB1v773+QSQiogAtQmY57bEU8K6mXw+APl+AFITEaA2AZ67Ek8Jqye1NwLU9n7mCZAPHeCdS9+XeEpYPfmMAPIdWdjyHQHkO6r1D/oJAAD//wAAAP//NI7BCsIwEER/JewHWIuIIE0vnnoQBL8g2m2zqNmwHRX/3lTsbd4c5k2ToyaGXE/mBk3oek81OXwye0p60PRim0QTVW2Tw8jHYKOkyd15gKf1akfOZIxLhuZfuyV3UUAfC0UOPdtMGyomxQL/3TPjmZ2acEJAEXrKarAgKIa9lF/W9fV8o3qr3abIjPYLAAD//wMAUEsDBBQABgAIAAAAIQD2YLRBuAcAABEiAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbOxazY8btxW/B8j/QMxd1szoe2E50Kc39u564ZVd5EhJlIZeznBAUrsrFAEK59RLgQJp0UuB3nooigZogAa55I8xYCNN/4g8ckaa4YqKvf5AkmJ3LzPU7z3+5r3HxzePc/eTq5ihCyIk5UnXC+74HiLJjM9psux6TybjSttDUuFkjhlPSNdbE+l9cu/jj+7iAxWRmCCQT+QB7nqRUulBtSpnMIzlHZ6SBH5bcBFjBbdiWZ0LfAl6Y1YNfb9ZjTFNPJTgGNQ+WizojKCJVund2ygfMbhNlNQDMybOtGpiSRjs/DzQCLmWAybQBWZdD+aZ88sJuVIeYlgq+KHr+ebPq967W8UHuRBTe2RLcmPzl8vlAvPz0MwpltPtpP4obNeDrX4DYGoXN2rr/60+A8CzGTxpxqWsM2g0/XaYY0ug7NKhu9MKaja+pL+2wznoNPth3dJvQJn++u4zjjujYcPCG1CGb+zge37Y79QsvAFl+OYOvj7qtcKRhTegiNHkfBfdbLXbzRy9hSw4O3TCO82m3xrm8AIF0bCNLj3FgidqX6zF+BkXYwBoIMOKJkitU7LAM4jiXqq4REMqU4bXHkpxwiUM+2EQQOjV/XD7byyODwguSWtewETuDGk+SM4ETVXXewBavRLk5TffvHj+9Yvn/3nxxRcvnv8LHdFlpDJVltwhTpZluR/+/sf//fV36L///tsPX/7JjZdl/Kt//v7Vt9/9lHpYaoUpXv75q1dff/XyL3/4/h9fOrT3BJ6W4RMaE4lOyCV6zGN4QGMKmz+ZiptJTCJMLQkcgW6H6pGKLODJGjMXrk9sEz4VkGVcwPurZxbXs0isFHXM/DCKLeAx56zPhdMAD/VcJQtPVsnSPblYlXGPMb5wzT3AieXg0SqF9EpdKgcRsWieMpwovCQJUUj/xs8JcTzdZ5Radj2mM8ElXyj0GUV9TJ0mmdCpFUiF0CGNwS9rF0FwtWWb46eoz5nrqYfkwkbCssDMQX5CmGXG+3ilcOxSOcExKxv8CKvIRfJsLWZl3Egq8PSSMI5GcyKlS+aRgOctOf0hhsTmdPsxW8c2Uih67tJ5hDkvI4f8fBDhOHVypklUxn4qzyFEMTrlygU/5vYK0ffgB5zsdfdTSix3vz4RPIEEV6ZUBIj+ZSUcvrxPuL0e12yBiSvL9ERsZdeeoM7o6K+WVmgfEcLwJZ4Tgp586mDQ56ll84L0gwiyyiFxBdYDbMeqvk+IhDJJ1zW7KfKISitkz8iS7+FzvL6WeNY4ibHYp/kEvG6F7lTAYnRQeMRm52XgCYXyD+LFaZRHEnSUgnu0T+tphK29S99Ld7yuheW/N1ljsC6f3XRdggy5sQwk9je2zQQza4IiYCaYoiNXugURy/2FiN5XjdjKKbewF23hBiiMrHonpsnrip8TLAS//Hlqnw9W9bgVv0u9sy+vHF6rcvbhfoW1zRCvklMC28lu4rotbW5LG+//vrTZt5ZvC5rbgua2oHG9gn2QgqaoYaC8KVo9pvET7+37LChjZ2rNyJE0rR8JrzXzMQyanpRpTG77gGkEl/p5YAILtxTYyCDB1W+ois4inEJ/KDBdzKXMVS8lSrmEtpEZNv1Uck23aT6t4mM+z9qdpr/kZyaUWBXjfgMaT9k4tKpUhm628kHNb0PdsF2aVuuGgJa9CYnSZDaJmoNEazP4GhK6c/Z+WHQcLNpa/cZVO6YAaluvwHs3grf1rteoZ4ygIwc1+lz7KXP1xrvaOe/V0/uMycoRAK3FXU93NNe9j6efLgu1N/C0RcI4JQsrm4TxlSnwZARvw3l0lvvuPxVwN/V1p3CpRU+bYrMaChqt9ofwtU4i13IDS8qZgiXoEtZ4CIvOQzOcdr0F9I3hMk4heKR+98JsCYcvMyWyFf82qSUVUg2xjDKLm6yT+SemigjEaNz19PNvw4ElJolk5DqwdH+p5EK94H5p5MDrtpfJYkFmquz30oi2dHYLKT5LFs5fjfjbg7UkX4G7z6L5JZqylXiMIcQarUB7d04lHB8EmavnFM7DtpmsiL9rO1Oe/a1DriIfY5ZGON9Sytk8g5sNZUvH3G1tULrLnxkMumvC6VLvsO+87b5+r9aWK/bHTrFpWmlFb5vubPrhdvkSq2IXtVhluft6zu1skh0EqnObePe9v0StmMyiphnv5mGdtPNRm9p7rAhKu09zj922m4TTEm+79YPc9ajVO8SmsDSBbw7Oy2fbfPoMkscQThFXLDvtZgncmdIyPRXGt1M+X+eXTGaJJvO5LkqzVP6YLBCdX3W90FU55ofHeTXAEkCbmhdW2FbQWe3Zgnqzy0WzBbsVzsrYa/WqLbyV2ByzboVNa9FFW11tTtR1rW5m1g7LntqkYWMpuNq1IrTJBYbSOTvMzXIv5JkrlVfacIVWgna93/qNXn0QNgYVv90YVeq1ul9pN3q1Sq/RqAWjRuAP++HnQE9FcdDIvnwYw2kQW+ffP5jxnW8g4s2B150Zj6vcfONQNd4330AE4f5vIMCRQCscBfWwFw4qg2HQrNTDYbPSbtV6lUHYHIY92LSb497nHrow4KA/HI7HjbDSHACu7vcalV6/Nqg026N+OA5G9aEP4Hz7uYK3GJ1zc1vApeF170cAAAD//wMAUEsDBBQABgAIAAAAIQCArhGptQIAALEGAAANAAAAeGwvc3R5bGVzLnhtbKxVTW/bMAy9D9h/EHR3ZbtxlgS2i6apgQJdMaAdsKtiy4lQfRiS0job9t9H2U7joMM2tLvEFEk9PpIik160UqAnZizXKsPRWYgRU6WuuNpk+OtDEcwwso6qigqtWIb3zOKL/OOH1Lq9YPdbxhwCCGUzvHWuWRBiyy2T1J7phimw1NpI6uBoNsQ2htHK+ktSkDgMp0RSrnCPsJDlv4BIah53TVBq2VDH11xwt++wMJLl4majtKFrAVTbaEJL1EZTE6PWHIJ02ldxJC+Ntrp2Z4BLdF3zkr2mOydzQssjEiC/DSlKSBif5N6aNyJNiGFP3LcP52mtlbOo1DvlMhwDUV+CxaPSz6rwJujw4JWn9jt6ogI0ESZ5WmqhDXLQOqhcp1FUst7jsnHaojtqjH72vjWVXOx7W+wVXcsHZ8mhAV5JPJme0jHYzFv+E3IXwEIELsQo6V6Rp/A6HDOqACsa5Id9A9kpeMg9QTD91Xtj6D6Kk9EF0gXM07U2FQzOody+sr0qTwWrHSRq+Gbrv0438LvWzsHjytOK041WVPgiHW4MAqRTMiHu/XB9q0+w2xqpnSyku6kyDGPqy3sQIZFB7PH6g8cfo/XY74ZFbX2KD4gj2iekX8Ij3/QM3/ltIOBhDhBovePCcfUbwoBZtccShL4Dzk92V5yXKFCJitV0J9zDizHDR/kzq/hOwiwMXl/4k3YdRIaP8q3vVDT1MVjrbi08XPiineEZ/nG9/DRfXRdxMAuXs2ByzpJgnixXQTK5Wq5WxTyMw6ufo/3yju3SrcM8hbldWAE7yAzJDuTvj7oMjw49/e6NAu0x93k8DS+TKAyK8zAKJlM6C2bT8yQokiheTSfL66RIRtyTN26hkERRv888+WThuGSCq0OvDh0aa6FJcPxDEuTQCXL8r8l/AQAA//8DAFBLAwQUAAYACAAAACEAobevW/kAAAAaAwAAFAAAAHhsL3NoYXJlZFN0cmluZ3MueG1sbNLNSsQwFAXgveA7hKzrpE36I5JmFgMy60EfILRxWmiT2psO+vZWEBFzlvfk3O9uoo8f88RubqUx+JYXh5wz57vQj/7a8teX54dHziha39speNfyT0f8aO7vNFFk+66nlg8xLk9CUDe42dIhLM7vL29hnW3cx/UqaFmd7WlwLs6TkHlei9mOnrMubD62XEnONj++b+70GxhNo9HRnAstotHie/pJ5P/kUmRJa89QT4HdMrmQtM5J5yLBTQluyiy9KbPUU8BTwFPAU8ArgVcCrwReCbwKeBXwKuBVwKuBVwOvBl4NvAZ4DfAa4DV/PbH/bfMFAAD//wMAUEsDBBQABgAIAAAAIQA7bTJLwQAAAEIBAAAjAAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHOEj8GKwjAURfcD/kN4e5PWhQxDUzciuFXnA2L62gbbl5D3FP17sxxlwOXlcM/lNpv7PKkbZg6RLNS6AoXkYxdosPB72i2/QbE46twUCS08kGHTLr6aA05OSonHkFgVC7GFUST9GMN+xNmxjgmpkD7m2UmJeTDJ+Ysb0Kyqam3yXwe0L0617yzkfVeDOj1SWf7sjn0fPG6jv85I8s+ESTmQYD6iSDnIRe3ygGJB63f2nmt9DgSmbczL8/YJAAD//wMAUEsDBBQABgAIAAAAIQASwiSvOgMAAOwOAAAnAAAAeGwvcHJpbnRlclNldHRpbmdzL3ByaW50ZXJTZXR0aW5nczEuYmlu7FfNUhNBEP6SoKX4xyNYnriEJBDAUFySLLGWyp/ZgHhzIQPZIuxu7W5MwPLG1bNVPoMHDx64+RIefQHLJ/CifjPJCgkUooairDhb0zPT09vz7ZfurkkOHhwEaEJwdh8lFJBHHEU8xAIySHKl4Ql3fGVhUfpcTVMvW2Qidv0Tpu7GPiAaQQRvbqVvNDjew0Y0iihljKss0sp6NCLSdyPHqMTA/p3tkW4MHKPp5bUH6EY+xpYnv3z9Nn/e6Xf6m7ER4vzv6t9iIIyri6Du0tgo1Vel7RSakRfIYREp5swCZYHxHldRr6lsSmOOWVSgLse1tIpTk6Fujs8ixxTmaZ+hfEmPuu22g5xlo1CplYzKWi2/gtqKoRWLWLMtT/hyVjVd4RnWgUA2jZJoWGZ93xUw6tmylq1pqLSD0Iu5JTSnY2PV2ayaO6LiNYQHIzDthuk1UPEsYQdmYDk2qpVavZbV6/ROO+XhcdtsWcE+yo63Z7aQd1otMxColJWNscVde4e7toDWdluii/WVWl3PZ4uoCd9ptZVjraovJJNddunB8UpOQ/RmvxUky5PAelorhb/VerWqv3r6+vM0vby9Bhyxy3bI8SbH2+xH7DarVrL/nDywydoXwMUSEnx8bKlKuAeT8xnswaJGVkiffZuWM1w71CfQ4Z6NBlcd7iYwS+8pVs0ExzSly/ekRaDkzoDm5Dm7rKj79OHQvqE86XzXJcj37C4122cwNFrcSUahxC3RXxT3NvGaZEL0se8qlMeYZ0+hHjXXEnOKvP8NZonyXZ/n3hcMwr56nofjoxfPMi52+fWpIZYvg+Mkq9Kfx/PznyhlHoa4h6Pj6mNjmGeJu4eySdxdRnrrl3nYYS50WCM6zKcZldEy7zd4qyqqWM2wwsscs/uZ45MPkxVFKM/P1Dk+q8DpNsjP2efICiRrUHiicaKaSY9u3791Cf7jqsr5rHYmv673RbL2yibHw4nePU3Ou/15LxaWsEqmNqHzPRdtesgpX2eAHBNVyEtWseHAYHy02LfIzTi3ZV72w/u+nB/XkiVmmGDeWIw+g/KAqyKjyqRO6serhfGjk4sKb5Xn/vEZI2p+AAAA//8DAFBLAwQUAAYACAAAACEA1JRDL0YBAABvAgAAEQAIAWRvY1Byb3BzL2NvcmUueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJJfT8MgFMXfTfwODe8ttFM3Sdsl/tmTS0yc0fhG4G4jFkqA2e3bS9ut1swHH+Gc++PcE/L5XlXRF1gna12gNCEoAs1rIfWmQK+rRTxDkfNMC1bVGgp0AIfm5eVFzg3ltYVnWxuwXoKLAkk7yk2Btt4birHjW1DMJcGhg7iurWI+HO0GG8Y/2QZwRsgNVuCZYJ7hFhibgYiOSMEHpNnZqgMIjqECBdo7nCYp/vF6sMr9OdApI6eS/mDCTse4Y7bgvTi4904OxqZpkmbSxQj5U/y+fHrpVo2lbrvigMpccMotMF/b8nHPVBSKEjvuQ805HmltjxVzfhkqX0sQd4dz+7kl0Ltl+idARCEe7Zc5KW+T+4fVApUZya5jchtn0xWZUpLRbPbRJvg138btL9Qxx/+JV5SQEfEEKHN89kXKbwAAAP//AwBQSwMEFAAGAAgAAAAhAGFJCRCJAQAAEQMAABAACAFkb2NQcm9wcy9hcHAueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnJJBb9swDIXvA/ofDN0bOd1QDIGsYkhX9LBhAZK2Z02mY6GyJIiskezXj7bR1Nl66o3ke3j6REndHDpf9JDRxVCJ5aIUBQQbaxf2lXjY3V1+FQWSCbXxMUAljoDiRl98UpscE2RygAVHBKxES5RWUqJtoTO4YDmw0sTcGeI272VsGmfhNtqXDgLJq7K8lnAgCDXUl+kUKKbEVU8fDa2jHfjwcXdMDKzVt5S8s4b4lvqnszlibKj4frDglZyLium2YF+yo6MulZy3amuNhzUH68Z4BCXfBuoezLC0jXEZtepp1YOlmAt0f3htV6L4bRAGnEr0JjsTiLEG29SMtU9IWT/F/IwtAKGSbJiGYzn3zmv3RS9HAxfnxiFgAmHhHHHnyAP+ajYm0zvEyznxyDDxTjjbgW86c843XplP+id7HbtkwpGFU/XDhWd8SLt4awhe13k+VNvWZKj5BU7rPg3UPW8y+yFk3Zqwh/rV878wPP7j9MP18npRfi75XWczJd/+sv4LAAD//wMAUEsBAi0AFAAGAAgAAAAhAEE3gs9uAQAABAUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAtVUwI/QAAABMAgAACwAAAAAAAAAAAAAAAACnAwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEAIEV3vmQDAACpCAAADwAAAAAAAAAAAAAAAADMBgAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhAIE+lJfzAAAAugIAABoAAAAAAAAAAAAAAAAAXQoAAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhAGNI/XhLAwAAdQkAABgAAAAAAAAAAAAAAAAAkAwAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQItABQABgAIAAAAIQD2YLRBuAcAABEiAAATAAAAAAAAAAAAAAAAABEQAAB4bC90aGVtZS90aGVtZTEueG1sUEsBAi0AFAAGAAgAAAAhAICuEam1AgAAsQYAAA0AAAAAAAAAAAAAAAAA+hcAAHhsL3N0eWxlcy54bWxQSwECLQAUAAYACAAAACEAobevW/kAAAAaAwAAFAAAAAAAAAAAAAAAAADaGgAAeGwvc2hhcmVkU3RyaW5ncy54bWxQSwECLQAUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAAAAAAAAAAAAAAAFHAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECLQAUAAYACAAAACEAEsIkrzoDAADsDgAAJwAAAAAAAAAAAAAAAAAHHQAAeGwvcHJpbnRlclNldHRpbmdzL3ByaW50ZXJTZXR0aW5nczEuYmluUEsBAi0AFAAGAAgAAAAhANSUQy9GAQAAbwIAABEAAAAAAAAAAAAAAAAAhiAAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAGFJCRCJAQAAEQMAABAAAAAAAAAAAAAAAAAAAyMAAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAAwADAAmAwAAwiUAAAAA'
          };
          requestPayload = payload;
          break;
        }
      case MESSAGE_ACTIONS.OPEN_URL:
        {
          const payload: IOpenURLPayload = {
            URL: 'https://nashefsys.com'
          };
          requestPayload = payload;
          break;
        }
    }

    this._webviewBridgeService.sendMessageToNative(action, requestPayload)
      .then(x => {
        const response = x as IResponseMessage;
        this.resultSource = `then | response is null: ${!response}`;
        this.result = response;
      })
      .catch(e => {
        const response = e as IResponseMessage;
        this.resultSource = `catch | response is null: ${!response}`;
        this.result = response;
      });
  }
}
